# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-bd42a3d5-0437-4b9e-9875-7ce488c854c1";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-bd42a3d5-0437-4b9e-9875-7ce488c854c1".device = "/dev/disk/by-uuid/bd42a3d5-0437-4b9e-9875-7ce488c854c1";

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-bd42a3d5-0437-4b9e-9875-7ce488c854c1";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/luks-bd42a3d5-0437-4b9e-9875-7ce488c854c1";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6BD6-1E62";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-f96690cc-e3a6-4bf1-add9-1af4eed8caa3";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
